spring.application.name=oauth-service

internal.shared-secret=${INTERNAL_SHARED_SECRET}

server.port=8084

management.endpoints.web.exposure.include=health,info

management.endpoint.health.show-details=always

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.health-check-url=http://host.docker.internal:8084/actuator/health