spring.application.name=oauth-service

server.port=8084

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.health-check-url=http://host.docker.internal:8084/actuator/health

spring.config.import=consul:localhost:8500
spring.cloud.consul.config.format=yaml
spring.cloud.consul.config.data-key=data