spring.application.name=gateway-service


server.port=8083

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.health-check-url=http://host.docker.internal:8083/actuator/health

spring.config.import=consul:localhost:8500
spring.cloud.consul.config.format=yaml
spring.cloud.consul.config.data-key=data