spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/loan_db
    username: postgres
    password: password123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

minio:
  url: http://minio:9000
  access-key: minioadmin
  secret-key: minioadminpassword
  bucket: loan-documents
