spring.application.name=account-service

server.port=8081

management.endpoints.web.exposure.include=health,info

management.endpoint.health.show-details=always

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.health-check-url=http://host.docker.internal:8081/actuator/health