spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: postgres
    password: ${SPRING_DATASOURCE_PASSWORD:mlk123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
